name: pystream-example
dependencies:
  - pip
  - pip:
    - -e .
    - python-dotenv>=0.5.1
    - awscli
    - awscli-plugin-endpoint
  - setuptools
  - ipykernel
  - wheel
  - flake8
  - sphinx
  - click
  - coverage
  - geopandas=0.4.0
  - rasterio=1.0.14
  - python=3
