name: pystream-example
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - -e .
    - python-dotenv>=0.5.1
    - awscli
    - awscli-plugin-endpoint
    - richdem==0.3.4
    - pygeoprocessing==1.6.0
    - salem==0.2.3
  - setuptools
  - ipykernel
  - wheel
  - flake8
  - sphinx
  - click
  - coverage
  - jupyter=1.0.0
  - cython=0.29.3
  - pandas=0.24.0  
  - geopandas=0.4.0
  - rasterio=1.0.14
  - dask=1.1.0
  - joblib=0.13.1
  - netcdf4=1.4.2
  - xarray=0.11.3
  - python=3
