name: pystream-example
dependencies:
  - pip
  - pip:
    - -e .
    - python-dotenv>=0.5.1
    - awscli
    - awscli-plugin-endpoint
    - richdem==0.3.4
    - pygeoprocessing==1.6.0
  - setuptools
  - ipykernel
  - wheel
  - flake8
  - sphinx
  - click
  - coverage
  - cython=0.29.3
  - geopandas=0.4.0
  - rasterio=1.0.14
  - python=3
